#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0

config:
  coap:
    # coapsPort: 5684
    coapsPort: 55684
    path: "sng"

    deduplicator: NO_DEDUPLICATOR
    maxActivePeers: 20000
    maxMessageSize: 1024
    maxPeerInactivityPeriod: 24h
    maxResourceBodySize: 8192
    preferredBlockSize: 1024

  udp:
    udpReceiveBufferSize: 8192
    udpSendBufferSize: 8192
    healthStatusInterval: 60
    healthStatusIntervalUnit: SECONDS
