#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: prometheus

config:
  coap:
    coaps-port: 55684
    path: "sng"

    deduplicator: NO_DEDUPLICATOR
    max-active-peers: 20000
    max-message-size: 1024
    max-peer-inactivity-period: 24h
    maxr-esource-body-size: 8192
    preferred-block-size: 1024

  http:
    url: "http://localhost:9000"
    connection-timeout: 5000ms

  udp:
    udp-receive-buffer-size: 8192
    udp-send-buffer-size: 8192
    health-status-interval-in-seconds: 60
