#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0

config:
  coap:
    coaps-port: 55684
    path: "sng"

    deduplicator: NO_DEDUPLICATOR
    max-active-peers: 20000
    max-message-size: 1024
    max-peer-inactivity-period: 24h
    max-resource-body-size: 8192
    preferred-block-size: 1024

  http:
    url: "localhost:9000/sng-test"
    protocol: "http"
    ssl-bundle: "sngSslBundle"

    connection-timeout: 5000ms
    response-timeout: 5000ms

  udp:
    udp-receive-buffer-size: 8192
    udp-send-buffer-size: 8192
    health-status-interval: 60
    health-status-interval-unit: SECONDS

  psk:
    default-id: "867787050253370"
    default-key: "ABCDEFGHIJKLMNOP"

spring:
  ssl:
    bundle:
      jks:
        sngSslBundle:
          truststore:
            location: "classpath:ssl/truststore.jks"
            password: "123456"
            type: "PKCS12"